/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_bob_nopush_NoPushService */

#ifndef _Included_sun_bob_nopush_NoPushService
#define _Included_sun_bob_nopush_NoPushService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_bob_nopush_NoPushService
 * Method:    entry
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_sun_bob_nopush_NoPushService_entry
  (JNIEnv *, jobject, jstring, jint,jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
