/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_bob_nopushtest_MainActivity */

#ifndef _Included_sun_bob_nopushtest_MainActivity
#define _Included_sun_bob_nopushtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
